package com.example.twogether.notification.entity;

public enum NotificationTitle {

    INVITED_WORKSPACE_COLLABORATOR,
    EXCLUDED_WORKSPACE_COLLABORATOR,

    INVITED_BOARD_COLLABORATOR,
    EXCLUDED_BOARD_COLLABORATOR,

    INVITED_CARD_COLLABORATOR,
    EXCLUDED_CARD_COLLABORATOR,

    CARD_CREATED,
    CARD_EDITED,

    CARD_FILE_UPLOADED,
    CARD_DUE_EDITED,

    CARD_COMMENT_CREATED,
    CARD_COMMENT_EDITED,
    CARD_CHECKLIST_CREATED,
    CARD_CHECKLIST_EDITED,
}

